# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/14b6e8da-d76f-4d6d-af2d-199ef907585c";
      fsType = "btrfs";
      options = [ "subvol=@" "noatime" "compress=zstd:3" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/14b6e8da-d76f-4d6d-af2d-199ef907585c";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "compress=zstd:3" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/14b6e8da-d76f-4d6d-af2d-199ef907585c";
      fsType = "btrfs";
      options = [ "subvol=@root" "noatime" "compress=zstd:3" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/14b6e8da-d76f-4d6d-af2d-199ef907585c";
      fsType = "btrfs";
      options = [ "subvol=@srv" "noatime" "compress=zstd:3" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/14b6e8da-d76f-4d6d-af2d-199ef907585c";
      fsType = "btrfs";
      options = [ "subvol=@swap" "noatime" "compress=zstd:3" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/14b6e8da-d76f-4d6d-af2d-199ef907585c";
      fsType = "btrfs";
      options = [ "subvol=@var" "noatime" "compress=zstd:3" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e415a7df-5ff0-4d80-8b94-d1b26146e560";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd:3" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/media/extra" =
    { device = "/dev/disk/by-uuid/f077af6b-3c07-439a-997c-1ab75095e1fb";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd:3" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0CA3-D7F0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [{
    device = "/swap/swapfile";
    options = [ "discard=async" ];
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
